import express from "express";
import helmet from "helmet";
import cors from "cors";
import cookieParser from "cookie-parser";
import routes from "./routes";
import { env } from "./config/env";
import { errorHandler, notFound } from "./middlewares/error.middleware";
const allowedOrigins = [env.DEV_CLIENT_ORIGIN, env.PROD_CLIENT_ORIGIN];
const app = express();
app.use(helmet());
app.use(cors({ origin: allowedOrigins, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use("/api/v1", routes);
app.use(notFound);
app.use(errorHandler);
export default app;
